# Generated by Django 5.1.2 on 2025-03-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0013_add_library_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="librarysettings",
            name="library",
        ),
    ]
