# Generated by Django 5.0.12 on 2025-05-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0022_remove_orderitem_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=511, null=True, verbose_name="Отдел или Институт"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="fullname",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ФИО"),
        ),
    ]
