# Generated by Django 5.0.12 on 2025-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0023_userprofile_department_userprofile_fullname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Заказана"),
                    ("handed", "Выдана"),
                    ("returned", "Возвращена"),
                    ("cancelled", "Не найдена"),
                    ("analogous", "Подобран аналог"),
                ],
                default="ordered",
                max_length=255,
            ),
        ),
    ]
