# Generated by Django 5.2.6 on 2025-11-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0024_alter_orderitem_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="librarysettings",
            name="max_extensions",
        ),
        migrations.RemoveField(
            model_name="librarysettings",
            name="overdue_fine_per_day",
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="", verbose_name="Логотип на сервисе"),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="new_order_wait",
            field=models.FloatField(default=1, verbose_name="Срок ожидания нового заказа (в часах)"),
        ),
        migrations.AddField(
            model_name="librarysettings",
            name="processing_order_wait",
            field=models.FloatField(default=0.5, verbose_name="Срок задержки исполнения заказа (в часах)"),
        ),
        migrations.AlterField(
            model_name="librarysettings",
            name="max_books_per_order",
            field=models.PositiveIntegerField(default=7, verbose_name="Максимальное количество книг в заказе"),
        ),
        migrations.AlterField(
            model_name="librarysettings",
            name="max_books_per_reader",
            field=models.PositiveIntegerField(default=15, verbose_name="Максимальное количество книг на руках"),
        ),
        migrations.AlterField(
            model_name="librarysettings",
            name="max_borrow_days",
            field=models.PositiveIntegerField(default=2, verbose_name="Максимальное количество дней на выдачу"),
        ),
    ]
