# Generated by Django 5.2.6 on 2025-11-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0024_alter_orderitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="handed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="returned_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="to_return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
