# Generated by Django 5.1.2 on 2025-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0024_alter_orderitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="banned_status_external",
            field=models.BooleanField(blank=True, default=False, verbose_name="Статус бана во внешней системе"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="banned_status_our",
            field=models.BooleanField(blank=True, default=False, verbose_name="Статус бана в нашей системе"),
        ),
    ]
