# Generated by Django 5.1.2 on 2025-10-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0025_userprofile_banned_status_external_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="banned_status_external",
        ),
    ]
