# Generated by Django 5.1.2 on 2025-10-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0026_remove_userprofile_banned_status_external"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="banned_status_our",
            field=models.BooleanField(default=False, verbose_name="Статус бана в нашей системе"),
        ),
    ]
