# Generated by Django 5.2.6 on 2025-11-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0025_alter_orderitem_handed_date_and_more"),
        ("library_service", "0027_alter_userprofile_banned_status_our"),
    ]

    operations = []
