# Generated by Django 5.2.6 on 2025-11-27 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0025_remove_librarysettings_max_extensions_and_more"),
        ("library_service", "0028_merge_20251127_1342"),
    ]

    operations = []
