# Generated by Django 5.2.6 on 2026-02-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0029_merge_20251127_1348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="librarysettings",
            name="logo",
            field=models.FileField(blank=True, null=True, upload_to="logo/", verbose_name="Логотип на сервисе"),
        ),
    ]
