# Generated by Django 5.2.6 on 2026-02-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_service", "0030_alter_librarysettings_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_role",
            field=models.TextField(blank=True, null=True, verbose_name="Текущая роль"),
        ),
    ]
