[pytest]
DJANGO_SETTINGS_MODULE = library_service.tests.settings
python_files = test_*.py
asyncio_mode=auto
markers =
    integration: integration tests (may hit external services or mocks)
filterwarnings =
    ignore:The 'default' argument to fields is deprecated:marshmallow.warnings.RemovedInMarshmallow4Warning
    ignore:Passing field metadata as keyword arguments is deprecated:marshmallow.warnings.RemovedInMarshmallow4Warning
    ignore:The 'default' argument to fields is deprecated\. Use 'dump_default' instead\.:marshmallow.warnings.RemovedInMarshmallow4Warning
